export const ActionTypes = {
    LOGIN: 'USERS_LOGIN',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',
    SET_LANGUAGE: 'SET_LANGUAGE',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
    VERIFY_SUCCESS: 'VERIFY_SUCCESS',
    VERIFY_FAILED: 'VERIFY_FAILED',
    SITE_INFO_UPDATE: 'SITE_INFO_UPDATE',
    THEME_UPDATED: 'THEME_UPDATED',
    THEME_CLEARED: 'THEME_CLEARED',
    BRANDING_UPDATED: 'BRANDING_UPDATED',
    BRANDING_CLEARED: 'BRANDING_CLEARED',
    MODULE_UPDATED: 'MODULE_UPDATED'
};
