export const StorageKeys = {
    IS_AUTHENTICATED: 'IS_AUTHENTICATED',
    EMAIL: 'EMAIL',
    LOGIN_TOKEN: 'LOGIN_TOKEN',
    ID: 'ID',
    USER_NAME: 'USER_NAME',
    THEME: 'theme',
    EXCEL: 'excel',
    USER: 'USER',
    BRAND_TITLE: 'BRAND_TITLE',
    BRAND_DESCRIPTION: 'BRAND_DESCRIPTION',
    BRAND_LOGO_SMALL: 'BRAND_LOGO_SMALL',
    BRAND_LOGO_LARGE: 'BRAND_LOGO_LARGE'
};
